on:
  push:
  pull_request:
    branches:
      - master

name: test

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    container: ${{ matrix.config.image }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }} - ${{ matrix.config.bioc }} - ${{ matrix.config.image }})

    strategy:
      fail-fast: false
      matrix:
        config:
        #- { os: windows-latest, r: 'devel', bioc: 'devel'}
        - { os: windows-latest, r: '4.1', bioc: 'devel'}
        #- { os: macOS-latest, r: 'release', bioc: '3.12'}
        - { os: macOS-latest, r: '4.1', bioc: 'devel'}
        #- { os: ubuntu-16.04, r: 'release', bioc: '3.12', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}
        #- { os: ubuntu-16.04, r: 'devel', bioc: 'devel', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}
        - { os: ubuntu-latest, r: '4.1', image: 'bioconductor/bioconductor_docker:devel'}
        #- { os: ubuntu-latest, r: 'release', image: 'bioconductor/bioconductor_docker:RELEASE_3_12'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@master
        if: matrix.config.image == null
        with:
          r-version: ${{ matrix.config.r }}

      - name: Set BiocManager version
        if: matrix.config.image == null
        run: |
          install.packages('BiocManager')
          BiocManager::install(version = "${{ matrix.config.bioc }}", ask = FALSE)
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows' && matrix.config.image == null
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-bioc-${{ matrix.config.bioc }}-${{ hashFiles('depends.txt') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-bioc-${{ matrix.config.bioc }}-

      - name: Install R package dependencies
        run: |
          pkgs <- unique(grep("^#", readLines("depends.txt"), value = TRUE, invert = TRUE))
          BiocManager::install(pkgs, Ncpu = 2L)
        shell: Rscript {0}
      
      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Run test code
        run: |
          source("tests.R")
        shell: Rscript {0}
